### ISSUE TITLE
isWiFiEnable方法判断有时候会错误

### ISSUE THREAD

**Issue by houjiahui90** [ziecho/ZYNetworkAccessibity#5]
手机iPhone7真机 关闭应用的网络权限，然后连接到了Wifi   该方法一直返回NO

**Comment by ziecho** [comment]
请问你的系统版本是多少？出现这个问题的时候 状态栏有没有 Wi-Fi 的标志

**Comment by houjiahui90** [comment]
你好，系统版本为12.0.1  出现这个问题的时候状态栏有WiFi标志
interfaces变量获取到了信息，取出的en0  但是不明白最后的判断的逻辑，最终导致返回NO
interfaces != nil && interfaces.count > 0	这样判断理论上就有WiFi链接了吧？

**Comment by ziecho** [comment]
1.2 版本已解决此问题

出现此问题的原因为 CNCopyCurrentNetworkInfo 函数再 iOS12 上需要开启 `Access WiFi Information ` 权限才可以使用，针对此问题，已经采用了其他方法来解决，感谢反馈，
