### ISSUE TITLE
IOS12在拒绝的时候获取结果为checking,CTCellularData获取状态正常

### ISSUE THREAD

**Issue by HellowjingQiu** [ziecho/ZYNetworkAccessibity#6]
在初始化的时候主动获取状态

**Comment by ziecho** [comment]
1.2 版本已解决此问题

出现此问题的原因为 CNCopyCurrentNetworkInfo 函数再 iOS12 上需要开启 `Access WiFi Information ` 权限才可以使用，针对此问题，已经换了另一种检测方式，感谢反馈。
